channels:
  - anaconda
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip=23.1.2
  - python=3.8.16
  - pip:
    # --- Torch
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - torch==1.13.1+cu117
    - torchvision==0.14.1+cu117
    # --- SD dependencies
    - albumentations==0.4.3
    - opencv-python
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - transformers==4.19.2
    - webdataset==0.2.5
    - open-clip-torch==2.7.0
    - gradio==3.13.2
    - kornia==0.6
    - invisible-watermark>=0.1.5
    - streamlit-drawable-canvas==0.8.0
    # --- Data management
    - batch-dev==0.0.3
    # --- Config management
    - hydra-core==1.3.0
    - hydra-colorlog==1.2.0
    - rich
    # --- Lighting Optimization
    - pytorch-lightning==1.8.3
    - wandb==0.16.4
    - torchmetrics
    - einops==0.7.0
    - PyGLM==2.7.1
    - OpenEXR==3.2.3
    # --- OmniData for geometry prediction
    - git+https://github.com/EPFL-VILAB/omnidata
    - timm==0.9.16
